application: my-authtest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#- url: /signup
#  script: main.app
#  secure: always
  
#- url: /login
#  script: main.app
#  secure: always
  
#- url: /forgot
#  script: main.app
#  secure: always

- url: /static
  static_dir: static
  
- url: /admin/.*
  script: main.app
  login: admin
  
- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "latest" #"2.5.2"
  
- name: pycrypto
  version: "latest" #"2.6"
  
- name: ssl
  version: latest
  
- name: jinja2
  version: "2.6"